### ISSUE TITLE
Cannot See Leviton Fan in HomeKit

### ISSUE THREAD

**Issue by thehumanista** [tabrindle/homebridge-leviton#14]
Hello,

I had to redo my HOOBS setup because my box failed. I got a new HOOBS SD and got everything up and running except the Leviton plugin. This is the error I'm getting:

```
(node:3457) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'residentialAccountId' of undefined
at LevitonDecoraSmartPlatform.initialize (/home/hoobs/.hoobs/node_modules/homebridge-leviton/index.js:70:38)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-leviton/index.js:26:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any suggestions on getting mu Leviton plugin to work?

Thanks!

**Comment by tabrindle** [comment]
Don't have an awful lot of error handling around this in my code because I only have the one account - this error suggests you might be using a different Leviton account that doesn't have permissions to access everything?

**Comment by tabrindle** [comment]
Please check out the version 1.5.0. Should address your problem (possibly in more than one way). Open up a new issue with more debug logs with "loglevel": "debug" in your config if your issue persists after updating and rebooting.
